
name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v4
    - run: docker build . -t karthik09484/myrepo
    - run: echo "${{secrets.DOCKERHUB_PASSWORD}}" | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin 
    - run: docker push karthik09484/myrepo:latest